//! `.env` parsing / writing utilities shared by `cloak import` and
//! `cloak export`.
//!
//! We deliberately don't pull in a 3rd-party dotenv crate: the parser we
//! need is tiny, we want full control over edge cases (quoted values,
//! `export` prefix, trailing comments), and bringing in `dotenvy` /
//! `dotenv` adds another link to the supply-chain story for a few
//! dozen lines of code.

use std::path::Path;

use anyhow::{Context as _, Result};

/// Parsed key/value from a `.env` file.
#[derive(Debug, Clone)]
pub struct EnvEntry {
    /// Variable name. Always uppercase ASCII alphanumeric + underscore.
    pub key: String,
    /// Raw value (de-quoted).
    pub value: String,
}

/// Parse a `.env`-style file into `(key, value)` pairs in source order.
/// Skips blank lines and `#` comments. Tolerant of `export FOO=bar`
/// shell-prefix lines and surrounding quotes.
pub fn parse_dotenv(path: &Path) -> Result<Vec<EnvEntry>> {
    let raw = std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    Ok(parse_dotenv_str(&raw))
}

/// Parse the raw contents of a `.env` file.
pub fn parse_dotenv_str(input: &str) -> Vec<EnvEntry> {
    let mut out = Vec::new();
    for line in input.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let line = trimmed
            .strip_prefix("export ")
            .or_else(|| trimmed.strip_prefix("export\t"))
            .unwrap_or(trimmed);
        let Some(eq) = line.find('=') else {
            continue;
        };
        let key = line[..eq].trim();
        if !valid_env_key(key) {
            continue;
        }
        let raw_value = line[eq + 1..].trim();
        let value = dequote(raw_value);
        out.push(EnvEntry {
            key: key.to_string(),
            value,
        });
    }
    out
}

fn valid_env_key(key: &str) -> bool {
    let mut chars = key.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '_' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
}

/// Strip matching surrounding quotes and trim a trailing inline comment
/// when the value is unquoted.
fn dequote(s: &str) -> String {
    let s = s.trim();
    if s.len() >= 2 {
        let first = s.as_bytes()[0];
        let last = s.as_bytes()[s.len() - 1];
        if (first == b'"' && last == b'"') || (first == b'\'' && last == b'\'') {
            return s[1..s.len() - 1].to_string();
        }
    }
    // Strip an inline `# comment` for unquoted values; only when there's
    // a space before the `#` (so URLs with fragments survive).
    if let Some(idx) = s.find(" #") {
        return s[..idx].trim_end().to_string();
    }
    s.to_string()
}

/// Render entries to a `.env` body, double-quoting values that contain
/// whitespace or shell metacharacters.
pub fn render_dotenv(entries: &[(String, String)]) -> String {
    let mut out = String::new();
    out.push_str("# Generated by `cloak export`. PLAINTEXT — keep this file safe.\n");
    for (k, v) in entries {
        let needs_quote = v.is_empty()
            || v.contains(|c: char| {
                c.is_whitespace() || matches!(c, '"' | '\'' | '$' | '`' | '\\' | '#')
            });
        if needs_quote {
            // Escape backslashes and double quotes inside the value.
            let escaped: String = v
                .chars()
                .map(|c| match c {
                    '\\' => "\\\\".to_string(),
                    '"' => "\\\"".to_string(),
                    '\n' => "\\n".to_string(),
                    other => other.to_string(),
                })
                .collect();
            out.push_str(&format!("{k}=\"{escaped}\"\n"));
        } else {
            out.push_str(&format!("{k}={v}\n"));
        }
    }
    out
}

/// Discover `.env` files we'd reasonably expect a user to have. We look
/// in the cwd plus the parent directory; we don't recurse to avoid
/// surprising the user with files from sibling projects.
pub fn discover_envs(cwd: &Path) -> Vec<std::path::PathBuf> {
    let names = [".env", ".env.local", ".env.development", ".env.production"];
    let mut out = Vec::new();
    for n in names {
        let p = cwd.join(n);
        if p.is_file() {
            out.push(p);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_basic() {
        let input = "FOO=bar\nexport BAZ=\"qux quux\"\n# comment\nEMPTY=\nWITH_HASH=https://x#y\n";
        let v = parse_dotenv_str(input);
        assert_eq!(v[0].key, "FOO");
        assert_eq!(v[0].value, "bar");
        assert_eq!(v[1].key, "BAZ");
        assert_eq!(v[1].value, "qux quux");
        assert_eq!(v[2].key, "EMPTY");
        assert_eq!(v[2].value, "");
        assert_eq!(v[3].key, "WITH_HASH");
        assert_eq!(v[3].value, "https://x#y");
    }

    #[test]
    fn skips_invalid_keys() {
        let input = "1FOO=bad\nFOO BAR=bad\nGOOD=ok\n";
        let v = parse_dotenv_str(input);
        assert_eq!(v.len(), 1);
        assert_eq!(v[0].key, "GOOD");
    }

    #[test]
    fn render_quotes_when_needed() {
        let body = render_dotenv(&[
            ("A".into(), "b".into()),
            ("B".into(), "with space".into()),
            ("C".into(), "with\"quote".into()),
        ]);
        assert!(body.contains("A=b\n"));
        assert!(body.contains("B=\"with space\"\n"));
        assert!(body.contains("C=\"with\\\"quote\"\n"));
    }
}
